# -*- coding: utf-8 -*-
"""Effect on a-site off-stoichiometric on NBT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rk_zwZ7enJYCGcQ1PwX500iPRjsBRoBb
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import r2_score, mean_absolute_error

import matplotlib.pyplot as plt
import seaborn as sns

props_path = "/content/nbt7bt_ml_dataset.csv"
df = pd.read_csv(props_path)

df.head()

props_path = "/content/nbt7bt_properties.csv"
df = pd.read_csv(props_path)

df.head()

# 1) Na_x vs d33
plt.figure(figsize=(6, 4))
plt.scatter(df["Bi_x"], df["d33"])
plt.xlabel("Bi_x (off-stoichiometry)")
plt.ylabel("d33 (pC/N)")
plt.title("Bi_x vs d33")
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 7))
corr = df.corr(numeric_only=True)

sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation Heatmap: Composition & Properties")
plt.tight_layout()
plt.show()

# 2) Sintering temperature vs d33, color by Na_x
plt.figure(figsize=(6, 4))
sc = plt.scatter(df["sinter_temp"], df["d33"], c=df["Na_x"], cmap="viridis")
plt.xlabel("Sintering Temperature (°C)")
plt.ylabel("d33 (pC/N)")
plt.title("d33 vs Sintering Temperature (color = Na_x)")
plt.colorbar(sc, label="Na_x")
plt.grid(True)
plt.show()

# 4) Na_x vs dielectric constant (epsilon_r)
plt.figure(figsize=(6, 4))
plt.scatter(df["Bi_x"], df["epsilon_r"])
plt.xlabel("Bi_x (off-stoichiometry)")
plt.ylabel("ε_r (dielectric constant)")
plt.title("Bi_x vs ε_r")
plt.grid(True)
plt.show()

# 3) Density vs d33
plt.figure(figsize=(6, 4))
plt.scatter(df["density"], df["d33"])
plt.xlabel("Density (g/cm³)")
plt.ylabel("d33 (pC/N)")
plt.title("Density vs d33")
plt.grid(True)
plt.show()

# features & targets

feature_cols = ["Na_x", "Bi_x", "Ba", "sinter_temp", "density"]
target_cols  = ["d33", "epsilon_r", "Ec", "grain_size"]

X = df[feature_cols].values
y = df[target_cols].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape, y_train.shape

# train RandomForestRegressor (multi-output)
base_rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

model_rf = MultiOutputRegressor(base_rf)
model_rf.fit(X_train, y_train)

# evaluation
y_pred = model_rf.predict(X_test)

r2  = r2_score(y_test, y_pred, multioutput='raw_values')
mae = mean_absolute_error(y_test, y_pred, multioutput='raw_values')

for i, target in enumerate(target_cols):
    print(f"{target}: R2 = {r2[i]:.3f}, MAE = {mae[i]:.3f}")

n_show = 5  # how many rows to show
idx = np.random.choice(len(X_test), size=n_show, replace=False)

X_sample = X_test[idx]
y_true_sample = y_test[idx]
y_pred_sample = model_rf.predict(X_sample)

df_compare = pd.DataFrame(X_sample, columns=feature_cols)

for i, t in enumerate(target_cols):
    df_compare[f"true_{t}"] = y_true_sample[:, i]
    df_compare[f"pred_{t}"] = y_pred_sample[:, i]

df_compare.round(3)

plt.figure(figsize=(10, 7))
corr = df.corr(numeric_only=True)

sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation Heatmap: Composition & Properties")
plt.tight_layout()
plt.show()

mean_d33 = df.groupby("Bi_x")["d33"].mean()

plt.figure(figsize=(6, 4))
mean_d33.plot(kind="bar")
plt.xlabel("Bi_x")
plt.ylabel("Mean d33 (pC/N)")
plt.title("Average d33 at Different Bi_x")
plt.grid(True)
plt.show()

mean_eps = df.groupby("Bi_x")["epsilon_r"].mean()

plt.figure(figsize=(6, 4))
mean_eps.plot(kind="bar")
plt.xlabel("Bi_x")
plt.ylabel("Mean Dielectric Constant (εr)")
plt.title("Average Dielectric Constant at Different Bi_x")
plt.grid(True)
plt.show()

pivot_d33 = df.pivot_table(
    values="d33",
    index="Bi_x",
    columns="sinter_temp",
    aggfunc="mean"
)

plt.figure(figsize=(7, 5))
sns.heatmap(pivot_d33, annot=True, fmt=".1f", cmap="viridis")
plt.title("d33 Heatmap: Na_x vs Sintering Temperature")
plt.xlabel("Sintering Temperature (°C)")
plt.ylabel("Bi_x")
plt.show()

mean_eps = df.groupby("Bi_x")["epsilon_r"].mean()

plt.figure(figsize=(6, 4))
mean_eps.plot(kind="bar")
plt.xlabel("Bi_x")
plt.ylabel("Mean Dielectric Constant (εr)")
plt.title("Average Dielectric Constant at Different Bi_x")
plt.grid(True)
plt.show()
# True vs predicted for d33
import numpy as np
import matplotlib.pyplot as plt

idx_d33 = target_cols.index("d33")

true_d33 = y_test[:, idx_d33]
pred_d33 = y_pred[:, idx_d33]

plt.figure(figsize=(5, 5))
plt.scatter(true_d33, pred_d33)
min_val = min(true_d33.min(), pred_d33.min())
max_val = max(true_d33.max(), pred_d33.max())
plt.plot([min_val, max_val], [min_val, max_val], "r--")  # y=x line
plt.xlabel("True d33 (pC/N)")
plt.ylabel("Predicted d33 (pC/N)")
plt.title("True vs Predicted d33")
plt.grid(True)
plt.show()

# True vs predicted for all targets
import matplotlib.pyplot as plt

n_targets = len(target_cols)
plt.figure(figsize=(5 * n_targets, 4))

for i, t in enumerate(target_cols):
    true_vals = y_test[:, i]
    pred_vals = y_pred[:, i]

    plt.subplot(1, n_targets, i+1)
    plt.scatter(true_vals, pred_vals)
    min_val = min(true_vals.min(), pred_vals.min())
    max_val = max(true_vals.max(), pred_vals.max())
    plt.plot([min_val, max_val], [min_val, max_val], "r--")
    plt.xlabel(f"True {t}")
    plt.ylabel(f"Pred {t}")
    plt.title(f"{t}: True vs Pred")
    plt.grid(True)

plt.tight_layout()
plt.show()

# single prediction example
# Example composition

sample = np.array([[0.00, 0.00, 0.07, 1150, 5.85]])  # Na_x, Bi_x, Ba, temp, density varying input
predicted = model_rf.predict(sample)[0]

for t, v in zip(target_cols, predicted):
    print(f"Predicted {t}: {v:.3f}")

